[WIP] feat: レクチャーページを新設して、コースから直接問題ページへのリンクをはらない
exKAZUu-Research/trace-dojo pull request #125
Opened 2024-09-19 11:36 UTC by hishiwat

Close #<IssueNumber>

## Self Check

- [ ] I've confirmed `All checks have passed` on PR page. (You may leave this box unchecked due to long workflows.)
  - PR title follows [Angular's commit message format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format).
    - PR title doesn't have `WIP:`.
  - All tests are passed.
    - Test command (e.g., `yarn test`) is passed.
    - Lint command (e.g., `yarn lint`) is passed.
- [ ] I've reviewed my changes on PR's diff view.

2024-09-20 05:13 UTC, exKAZUu commented
@hishiwat 問題のIDもuuidになっているように見えるけど、第N回の問題一覧ページだけにUUIDを入れたくて、それ以外は変更しないようにしてもらえんだろか

2024-09-20 12:58 UTC, hishiwat commented
@exkazuu 各lectureページですべての問題の`userProblemSessions`をフェッチするのは余分な気がするので、スキーマに`lectureId`を追加しても大丈夫でしょうか。

2024-09-21 13:16 UTC, exKAZUu commented
@hishiwat コンフリクト解消がミスっている気がするので、見直してもらえないだろうか。
例えば、 `BaseProblem.tsx` と `pageOnClient.tsx` はほぼ重複している。

2024-09-21 13:58 UTC, hishiwat commented
@exKAZUu 修正しました。

2024-09-21 14:18 UTC, exKAZUu requested changes
すまんが、 `git pull origin 101-feat-create-lecture-page` をした上で、コメントした点に対応してほしい。

2024-09-21 14:18 UTC, exKAZUu commented on src/problems/problemData.ts
> +export const UUIDs = [
`courseIdToProgramIdLists` と同じ形式、つまり、以下のように変更してもらえないだろうか。
```
{
  tuBeginner1: [
    '8d692b48-8c19-4679-8d8f-3f27a051d44d',
    ...
  ],
  tuBeginner2: [
    ...
  ],
}
```

2024-09-21 14:18 UTC, exKAZUu commented on src/app/(withAuth)/courses/[courseId]/[lectureId]/[programId]/pageOnClient.tsx
> +        languageId: 'java',
言語選択機能を削除したので、プログラム全体から `languageId` も消してしまってもらえないだろうか。

2024-09-21 14:18 UTC, exKAZUu commented on src/app/(withAuth)/courses/[courseId]/[lectureId]/LectureCard.tsx
> +'use client';
`.../courses/[courseId]/lectures/[lectureId]/...` というフォルダ構成にしてほしい。
同様に、問題については、 `.../courses/[courseId]/lectures/[lectureId]/problems/[problemId]/...` というフォルダ構成にしてほしい。

2024-09-22 07:42 UTC, exKAZUu approved these changes
LGTM :+1:

2024-09-22 07:42 UTC, merged