feat: 第1回講義のスライドのサンプルプログラムを問題として追加する
exKAZUu-Research/trace-dojo pull request #96
Opened 2024-09-11 02:21 UTC by hishiwat

Close #<IssueNumber>

## Self Check

- [ ] I've confirmed `All checks have passed` on PR page. (You may leave this box unchecked due to long workflows.)
  - PR title follows [Angular's commit message format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format).
    - PR title doesn't have `WIP:`.
  - All tests are passed.
    - Test command (e.g., `yarn test`) is passed.
    - Lint command (e.g., `yarn lint`) is passed.
- [ ] I've reviewed my changes on PR's diff view.

2024-09-11 02:24 UTC, hishiwat commented
![スクリーンショット 2024-09-11 111550](https://github.com/user-attachments/assets/e0600f41-b504-43bf-bf98-7e538f28b85e)

上記の問題では左下にカメをセットしただけで正答してしまいます。
後ろに戻るボタンを押した際に元にいた地点の色を白にする機能は削除したほうがいいでしょうか。

2024-09-11 03:52 UTC, exKAZUu commented
@hishiwat そうね、スライドと同じ仕様になるようにソフトウェア側を直してほしい。
それから、 `Java` のコードはスライドと同じ世界観にしてほしい（メソッド名が日本語であったり、クラスがTurtleであったりなど。）
`instrumented` さえ、動くコードになっていれば、 `java` や `js` はただ表示しているだけだから、どんな内容でも（実際には動かないコードでも）大丈夫。
あと、`js` はなくてOKです。プロパティごと消せるなら消してしまって、消せなければ、空文字などにしておいてほしい。

2024-09-13 06:53 UTC, exKAZUu requested changes
Javaコードのインデント周りが気になっているので、コメントを踏まえて、全体的に見直してほしい。

2024-09-13 06:53 UTC, exKAZUu commented on src/problems/problemData.ts
> +	public class Main {
まだ実際に動かしていないのだけど、インデントレベルが一つ多い気がするので、確認してほしい。つまり、
```java
	public class Main {
		public static void main(String[] args) {
			Turtle 亀 = new Turtle(); // sid
			亀.前に進む(); // sid
			亀.前に進む(); // sid
		}
}
```
ではなく、
```java
public class Main {
	public static void main(String[] args) {
		Turtle 亀 = new Turtle(); // sid
		亀.前に進む(); // sid
		亀.前に進む(); // sid
	}
}
```
ではなかろうか？他にも同じような箇所がたくさんあるので、見直してほしい。

2024-09-16 05:25 UTC, exKAZUu commented
@hishiwat すまんがコンフリクトを直してほしい

2024-09-17 08:41 UTC, merged